### ISSUE TITLE
links to paper and code

### ISSUE THREAD

**Issue by Randolph-zeng** [XDUWQ/DiffSketching#1]
Hi, I came across your paper on sketch guidance but found my downloaded pdf does not contain the appendix section. However I could not find this paper in arxiv or google any more. Did you guys take it off from arxiv or can you guys provide more detailed illustration to your methods? It will be greatly appreciated, thanks !

**Comment by XDUWQ** [comment]
Hi, thank you for your attention to our work. Our supplementary materials can be downloaded from this link: https://bmvc2022.mpi-inf.mpg.de/0067_supp.zip . Welcome to the bmvc official website for more information about this paper.

**Comment by wangqiang9** [comment]
> Hi, I came across your paper on sketch guidance but found my downloaded pdf does not contain the appendix section. However I could not find this paper in arxiv or google any more. Did you guys take it off from arxiv or can you guys provide more detailed illustration to your methods? It will be greatly appreciated, thanks !

Hi, thank you for your attention to our work. Our supplementary materials can be downloaded from this link: https://bmvc2022.mpi-inf.mpg.de/0067_supp.zip . Welcome to the bmvc official website for more information about this paper.
