### ISSUE TITLE
Request for Pretrained Model Sharing

### ISSUE THREAD

**Issue by sangminkim-99** [XDUWQ/DiffSketching#3]
Hi, @XDUWQ!

First of all, I want to express my appreciation for the impressive work you've shared!

I was wondering if there are any plans to share the pre-trained model associated with this project. 

Thank you for considering this request, and I look forward to your response.

Best regards,
Sang Min Kim

**Comment by wangqiang9** [comment]
Thank you for your attention. In the future, there will be plans to release images, pre trained models, and online operational services.
